<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JobSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('jobs')->insert([
            [
                'jobdesc_id' => '5',
                'title' => 'FullStack Development',
                'company' => 'PT. Telkom (persero)',
                'desc_company' => 'Perusahaan dalam bidang Teknologi Informasi',
                'area' => 'Bandung',
                'type' => 'Fulltime',
                'location' => 'Kerja di Kantor (WFO)',
                'position' => 'Developer',
                'desc_job' => '1. Good looking 2. Kaya 3. Punya Pajero',
                'salary' => 10000000,
                'gender' => 'Laki-Laki',
                'age' => 25,
                'study_id' => 3,
                'experience' => '2',
                'workday_start' => 'Senin',
                'workday_end' => 'Jumat',
                'workhour_start' => '09:00:00',
                'workhour_end' => '17:00:00',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'jobdesc_id' => '7',
                'title' => 'Digital marketing',
                'company' => 'AHM ',
                'desc_company' => 'Perusahaan dalam bidang kendaraan',
                'area' => 'Jakarta',
                'type' => 'Kontrak',
                'location' => 'Kerja di Rumah (WFH)',
                'position' => 'Bagian Pemasaran',
                'desc_job' => '1. Good looking',
                'salary' => 4000000,
                'gender' => 'Perempuan',
                'age' => 20,
                'study_id' => 1,
                'experience' => '1',
                'workday_start' => 'Senin',
                'workday_end' => 'Jumat',
                'workhour_start' => '09:00:00',
                'workhour_end' => '17:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jobdesc_id' => '2',
                'title' => 'Sales',
                'company' => 'PT. Buana Indah Kencana',
                'desc_company' => 'Perusahaan dalam bidang penjualan ponsel',
                'area' => 'Bandung',
                'type' => 'Fulltime',
                'location' => 'Kerja di Kantor (WFO)',
                'position' => 'Bagian Pemasaran',
                'desc_job' => '1. Berpenampilan menarik, 2. Dapat menarik minat client, 3. Jomblo',
                'salary' => 2500000,
                'gender' => 'Perempuan',
                'age' => '26',
                'study_id' => 1,
                'experience' => '1',
                'workday_start' => 'Senin',
                'workday_end' => 'Jumat',
                'workhour_start' => '09:00:00',
                'workhour_end' => '17:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jobdesc_id' => '7',
                'title' => 'Marketing',
                'company' => 'PT. Sukses Makmur',
                'desc_company' => 'Perusahaan distribusi makanan',
                'area' => 'Jakarta',
                'type' => 'Part-time',
                'location' => 'Kerja di Kantor (WFO)',
                'position' => 'Bagian Promosi',
                'desc_job' => '1. Kreatif dalam promosi, 2. Dapat bekerja dalam tim, 3. Jujur',
                'salary' => 2000000,
                'gender' => 'Laki-laki',
                'age' => '25',
                'study_id' => 1,
                'experience' => '2',
                'workday_start' => 'Senin',
                'workday_end' => 'Sabtu',
                'workhour_start' => '10:00:00',
                'workhour_end' => '15:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jobdesc_id' => '5',
                'title' => 'IT Support',
                'company' => 'PT. Digital Nusantara',
                'desc_company' => 'Perusahaan teknologi informasi',
                'area' => 'Surabaya',
                'type' => 'Fulltime',
                'location' => 'Kerja di Kantor (WFO)',
                'position' => 'Bagian Teknisi',
                'desc_job' => '1. Menguasai jaringan, 2. Mengatasi masalah IT, 3. Rajin',
                'salary' => 3000000,
                'gender' => 'Perempuan',
                'age' => '28',
                'study_id' => 4,
                'experience' => '1',
                'workday_start' => 'Senin',
                'workday_end' => 'Jumat',
                'workhour_start' => '08:00:00',
                'workhour_end' => '16:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jobdesc_id' => '5',
                'title' => 'Designer',
                'company' => 'PT. Kreatif Visual',
                'desc_company' => 'Perusahaan desain grafis',
                'area' => 'Bali',
                'type' => 'Kontrak',
                'location' => 'Kerja di Rumah (WFH)',
                'position' => 'Bagian Desain',
                'desc_job' => '1. Menguasai Adobe Suite, 2. Kreatif, 3. Pekerja keras',
                'salary' => 4000000,
                'gender' => 'Laki-laki',
                'age' => '23',
                'study_id' => 3,
                'experience' => '3',
                'workday_start' => 'Senin',
                'workday_end' => 'Jumat',
                'workhour_start' => '09:00:00',
                'workhour_end' => '18:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jobdesc_id' => '6',
                'title' => 'Customer Service',
                'company' => 'PT. Layanan Prima',
                'desc_company' => 'Perusahaan layanan pelanggan',
                'area' => 'Yogyakarta',
                'type' => 'Fulltime',
                'location' => 'Kerja di Kantor (WFO)',
                'position' => 'Bagian Layanan',
                'desc_job' => '1. Ramah, 2. Cepat tanggap, 3. Pandai berkomunikasi',
                'salary' => 2500000,
                'gender' => 'Perempuan',
                'age' => '24',
                'study_id' => 2,
                'experience' => '1',
                'workday_start' => 'Senin',
                'workday_end' => 'Sabtu',
                'workhour_start' => '08:00:00',
                'workhour_end' => '16:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jobdesc_id' => '9',
                'title' => 'HRD',
                'company' => 'PT. Sumber Day',
                'desc_company' => 'Perusahaan penyedia tenaga kerja',
                'area' => 'Medan',
                'type' => 'Fulltime',
                'location' => 'Kerja di Kantor (WFO)',
                'position' => 'Bagian Keuangan',
                'desc_job' => '1. Memahami undang-undang keuangan, 2. Memiliki pengalaman dibidang keuangan, 3. Komunikatif',
                'salary' => 3500000,
                'gender' => 'Laki-laki',
                'age' => '30',
                'study_id' => 4,
                'experience' => '2',
                'workday_start' => 'Senin',
                'workday_end' => 'Jumat',
                'workhour_start' => '09:00:00',
                'workhour_end' => '17:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jobdesc_id' => '6',
                'title' => 'Accountant',
                'company' => 'PT. Keuangan Maju',
                'desc_company' => 'Perusahaan konsultan keuangan',
                'area' => 'Semarang',
                'type' => 'Fulltime',
                'location' => 'Kerja di Kantor (WFO)',
                'position' => 'Bagian Akuntansi',
                'desc_job' => '1. Menguasai pembukuan, 2. Teliti, 3. Memiliki sertifikat akuntansi',
                'salary' => 4500000,
                'gender' => 'Perempuan',
                'age' => '27',
                'study_id' => 1,
                'experience' => '3',
                'workday_start' => 'Senin',
                'workday_end' => 'Jumat',
                'workhour_start' => '09:00:00',
                'workhour_end' => '17:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jobdesc_id' => '5',
                'title' => 'Software Engineer',
                'company' => 'PT. Teknologi Terdepan',
                'desc_company' => 'Perusahaan pengembang perangkat lunak',
                'area' => 'Makassar',
                'type' => 'Fulltime',
                'location' => 'Kerja di Kantor (WFO)',
                'position' => 'Bagian Pengembangan',
                'desc_job' => '1. Menguasai pemrograman, 2. Analitis, 3. Dapat bekerja di bawah tekanan',
                'salary' => 6000000,
                'gender' => 'Laki-laki',
                'age' => '23',
                'study_id' => 3,
                'experience' => '2',
                'workday_start' => 'Senin',
                'workday_end' => 'Jumat',
                'workhour_start' => '08:00:00',
                'workhour_end' => '16:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jobdesc_id' => '1',
                'title' => 'Content Writer',
                'company' => 'PT. Kreatif Media',
                'desc_company' => 'Perusahaan media dan konten',
                'area' => 'Bandung',
                'type' => 'Freelance',
                'location' => 'Kerja di Rumah (WFH)',
                'position' => 'Bagian Penulisan',
                'desc_job' => '1. Menguasai SEO, 2. Menulis konten kreatif, 3. Menguasai tata bahasa',
                'salary' => 3500000,
                'gender' => 'Perempuan',
                'age' => '26',
                'study_id' => 2,
                'experience' => '1',
                'workday_start' => 'Senin',
                'workday_end' => 'Jumat',
                'workhour_start' => '08:00:00',
                'workhour_end' => '17:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jobdesc_id' => '5',
                'title' => 'Graphic Designer',
                'company' => 'PT. Warna Indah',
                'desc_company' => 'Perusahaan percetakan dan desain',
                'area' => 'Malang',
                'type' => 'Fulltime',
                'location' => 'Kerja di Kantor (WFO)',
                'position' => 'Bagian Desain Grafis',
                'desc_job' => '1. Kreatif, 2. Menguasai desain grafis, 3. Menguasai software desain',
                'salary' => 3000000,
                'gender' => 'Laki-laki',
                'age' => '21',
                'study_id' => 3,
                'experience' => '2',
                'workday_start' => 'Senin',
                'workday_end' => 'Jumat',
                'workhour_start' => '08:00:00',
                'workhour_end' => '17:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jobdesc_id' => '4',
                'title' => 'Pengajar Bahasa',
                'company' => 'CV. Maju Maju Saja',
                'desc_company' => 'Lembaga pendidikan yang bergerak dalam bidang pengajaran bahasa asing',
                'area' => 'Depok',
                'type' => 'Fulltime',
                'location' => 'Kerja di Kantor (WFO)',
                'position' => 'Bagian Pengajar Bahasa Inggris',
                'desc_job' => '1. Kreatif, 2. Mudah bergaul dan ramah, 3. Menguasai bahasa Inggris',
                'salary' => 4000000,
                'gender' => 'Laki-laki',
                'age' => '23',
                'study_id' => 3,
                'experience' => '2',
                'workday_start' => 'Senin',
                'workday_end' => 'Jumat',
                'workhour_start' => '08:00:00',
                'workhour_end' => '17:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
